class Places{
  String? name;
  String? location;
  double? price;
  double? rate;
  int? reviewNumber;
  int? categoryIndex;
  String? networkImageLink;
  String? description;

  Places(
      {required this.name,
      required this.location,
      required this.price,
      required this.rate,
      required this.reviewNumber,
      required this.categoryIndex,
      required this.networkImageLink,
      required this.description});
}
List<Places> places = [
  Places(name: 'Mount Sinai', location: 'Egypt', price: 890, rate: 4.9, reviewNumber: 15000, categoryIndex: 0 , networkImageLink: 'https://reflectionstravel.net/images/tour/large/147-Mount-Sinai-St-Catherine-Monastery-from-Sharm-El-Sheikh-10441506422660.jpeg', description: 'The Greek Orthodox monastery of the God-trodden Mount Sinai is located at the very place where God appeared to Moses in the Burning Bush, beneath the Mount of the Decalogue. In the providence of God, it is at this site also that the holy relics of Saint Catherine are enshrined. This is the oldest continuously inhabited Christian monastery, with a history that can be traced back over seventeen centuries. The monastery predates the divisions of the Christian world, its origins extending to late antiquity.'),
  Places(name: 'Jabal Mousa', location: "Egypt", price: 980, rate: 4.8, reviewNumber: 17000, categoryIndex: 0, networkImageLink: 'https://www.connollycove.com/wp-content/uploads/2022/07/Mount-Sinai-Mountains-in-Egypt-1536x1024.jpg', description: 'Mount Sinai is one of the greatest mountains in Egypt that would be a shame to miss. Apparently, it is another mountain that the lands of Sinai embraces within its borders, situated near the city of Saint Catherine as well. It elevates at a height of 2,285 meters above sea level and goes by more than a few names, with Jabal Musa being the one most commonly used. '),
  Places(name: 'Abu Rumayl', location: 'Egypt', price: 750, rate: 4.7, reviewNumber: 13000, categoryIndex: 0, networkImageLink: 'https://farm9.staticflickr.com/8187/8128422531_2f8418c46f.jpg', description: 'Jabal Abu Rumayl is one of the famous mountains in Egypt that are located in Sinai, in south Sinai in particular. You may find the name with different variations, including Abu Rumail, for example. Many of the mountains around this region are characterised with the high elevation, attracting tourists from different places around the world, and this one is no exception.'),
  Places(name: 'Montazah', location: 'Alex', price: 550, rate: 4.6, reviewNumber: 16500, categoryIndex: 1, networkImageLink: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/25/8a/d4/location.jpg?w=1200&h=-1&s=1', description: 'Royal gardens of King Faruk. The king was the last Egyptian monarch.'),
  Places(name: 'Japan Gard', location: 'Helwan', price: 450, rate: 4.5, reviewNumber: 9000, categoryIndex: 1, networkImageLink: 'https://photos.wikimapia.org/p/00/01/78/76/02_big.jpg', description: 'This is a beautiful theme garden near the edge of what once was a beautiful winter escape from Cairo. Helwan has long since become an industrial city then later fell into despair.'),
  Places(name: 'Orman Gard', location: 'Giza', price: 650, rate: 4.6, reviewNumber: 14000, categoryIndex: 1, networkImageLink: 'https://www.egypttoday.com/siteimages/ArticleImgs/2021/3/15/136693-136693-%D8%A7%D8%B4%D9%83%D8%A7%D9%84-%D9%88%D8%A7%D9%84%D9%88%D8%A7%D9%86-%D8%A7%D9%84%D8%B2%D9%87%D9%88%D8%B1-(1).jpeg', description: 'The Orman Garden is one of the most famous Botanical gardens in Egypt. It is located at Giza, in Cairo.'),

];

List<List<Places>> place=[
  mountains,gardens,cinemas,aquaParks,malls,sea,island
];


List<Places> mountains = [
  Places(name: 'Mount Sinai', location: 'Egypt', price: 890, rate: 4.9, reviewNumber: 15000, categoryIndex: 0 , networkImageLink: 'https://reflectionstravel.net/images/tour/large/147-Mount-Sinai-St-Catherine-Monastery-from-Sharm-El-Sheikh-10441506422660.jpeg', description: 'The Greek Orthodox monastery of the God-trodden Mount Sinai is located at the very place where God appeared to Moses in the Burning Bush, beneath the Mount of the Decalogue. In the providence of God, it is at this site also that the holy relics of Saint Catherine are enshrined. This is the oldest continuously inhabited Christian monastery, with a history that can be traced back over seventeen centuries. The monastery predates the divisions of the Christian world, its origins extending to late antiquity.'),
  Places(name: 'Jabal Mousa', location: "Egypt", price: 980, rate: 4.8, reviewNumber: 17000, categoryIndex: 0, networkImageLink: 'https://www.connollycove.com/wp-content/uploads/2022/07/Mount-Sinai-Mountains-in-Egypt-1536x1024.jpg', description: 'Mount Sinai is one of the greatest mountains in Egypt that would be a shame to miss. Apparently, it is another mountain that the lands of Sinai embraces within its borders, situated near the city of Saint Catherine as well. It elevates at a height of 2,285 meters above sea level and goes by more than a few names, with Jabal Musa being the one most commonly used. '),
  Places(name: 'Abu Rumayl', location: 'Egypt', price: 750, rate: 4.7, reviewNumber: 13000, categoryIndex: 0, networkImageLink: 'https://farm9.staticflickr.com/8187/8128422531_2f8418c46f.jpg', description: 'Jabal Abu Rumayl is one of the famous mountains in Egypt that are located in Sinai, in south Sinai in particular. You may find the name with different variations, including Abu Rumail, for example. Many of the mountains around this region are characterised with the high elevation, attracting tourists from different places around the world, and this one is no exception.'),
];
List<Places> gardens = [
  Places(name: 'Montazah', location: 'Alex', price: 550, rate: 4.6, reviewNumber: 16500, categoryIndex: 1, networkImageLink: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/25/8a/d4/location.jpg?w=1200&h=-1&s=1', description: 'Royal gardens of King Faruk. The king was the last Egyptian monarch.'),
  Places(name: 'Japan Gard', location: 'Helwan', price: 450, rate: 4.5, reviewNumber: 9000, categoryIndex: 1, networkImageLink: 'https://photos.wikimapia.org/p/00/01/78/76/02_big.jpg', description: 'This is a beautiful theme garden near the edge of what once was a beautiful winter escape from Cairo. Helwan has long since become an industrial city then later fell into despair.'),
  Places(name: 'Orman Gard', location: 'Giza', price: 650, rate: 4.6, reviewNumber: 14000, categoryIndex: 1, networkImageLink: 'https://www.egypttoday.com/siteimages/ArticleImgs/2021/3/15/136693-136693-%D8%A7%D8%B4%D9%83%D8%A7%D9%84-%D9%88%D8%A7%D9%84%D9%88%D8%A7%D9%86-%D8%A7%D9%84%D8%B2%D9%87%D9%88%D8%B1-(1).jpeg', description: 'The Orman Garden is one of the most famous Botanical gardens in Egypt. It is located at Giza, in Cairo.'),
];
List<Places> cinemas = [
  Places(name: 'Mount Sinai', location: 'Egypt', price: 890, rate: 4.9, reviewNumber: 15000, categoryIndex: 0 , networkImageLink: 'https://reflectionstravel.net/images/tour/large/147-Mount-Sinai-St-Catherine-Monastery-from-Sharm-El-Sheikh-10441506422660.jpeg', description: 'The Greek Orthodox monastery of the God-trodden Mount Sinai is located at the very place where God appeared to Moses in the Burning Bush, beneath the Mount of the Decalogue. In the providence of God, it is at this site also that the holy relics of Saint Catherine are enshrined. This is the oldest continuously inhabited Christian monastery, with a history that can be traced back over seventeen centuries. The monastery predates the divisions of the Christian world, its origins extending to late antiquity.'),
  Places(name: 'Jabal Mousa', location: "Egypt", price: 980, rate: 4.8, reviewNumber: 17000, categoryIndex: 0, networkImageLink: 'https://www.connollycove.com/wp-content/uploads/2022/07/Mount-Sinai-Mountains-in-Egypt-1536x1024.jpg', description: 'Mount Sinai is one of the greatest mountains in Egypt that would be a shame to miss. Apparently, it is another mountain that the lands of Sinai embraces within its borders, situated near the city of Saint Catherine as well. It elevates at a height of 2,285 meters above sea level and goes by more than a few names, with Jabal Musa being the one most commonly used. '),
  Places(name: 'Abu Rumayl', location: 'Egypt', price: 750, rate: 4.7, reviewNumber: 13000, categoryIndex: 0, networkImageLink: 'https://farm9.staticflickr.com/8187/8128422531_2f8418c46f.jpg', description: 'Jabal Abu Rumayl is one of the famous mountains in Egypt that are located in Sinai, in south Sinai in particular. You may find the name with different variations, including Abu Rumail, for example. Many of the mountains around this region are characterised with the high elevation, attracting tourists from different places around the world, and this one is no exception.'),

];
List<Places> aquaParks = [
  Places(name: 'Mount Sinai', location: 'Egypt', price: 890, rate: 4.9, reviewNumber: 15000, categoryIndex: 0 , networkImageLink: 'https://reflectionstravel.net/images/tour/large/147-Mount-Sinai-St-Catherine-Monastery-from-Sharm-El-Sheikh-10441506422660.jpeg', description: 'The Greek Orthodox monastery of the God-trodden Mount Sinai is located at the very place where God appeared to Moses in the Burning Bush, beneath the Mount of the Decalogue. In the providence of God, it is at this site also that the holy relics of Saint Catherine are enshrined. This is the oldest continuously inhabited Christian monastery, with a history that can be traced back over seventeen centuries. The monastery predates the divisions of the Christian world, its origins extending to late antiquity.'),
  Places(name: 'Jabal Mousa', location: "Egypt", price: 980, rate: 4.8, reviewNumber: 17000, categoryIndex: 0, networkImageLink: 'https://www.connollycove.com/wp-content/uploads/2022/07/Mount-Sinai-Mountains-in-Egypt-1536x1024.jpg', description: 'Mount Sinai is one of the greatest mountains in Egypt that would be a shame to miss. Apparently, it is another mountain that the lands of Sinai embraces within its borders, situated near the city of Saint Catherine as well. It elevates at a height of 2,285 meters above sea level and goes by more than a few names, with Jabal Musa being the one most commonly used. '),
  Places(name: 'Abu Rumayl', location: 'Egypt', price: 750, rate: 4.7, reviewNumber: 13000, categoryIndex: 0, networkImageLink: 'https://farm9.staticflickr.com/8187/8128422531_2f8418c46f.jpg', description: 'Jabal Abu Rumayl is one of the famous mountains in Egypt that are located in Sinai, in south Sinai in particular. You may find the name with different variations, including Abu Rumail, for example. Many of the mountains around this region are characterised with the high elevation, attracting tourists from different places around the world, and this one is no exception.'),

];
List<Places> malls = [
  Places(name: 'Mount Sinai', location: 'Egypt', price: 890, rate: 4.9, reviewNumber: 15000, categoryIndex: 0 , networkImageLink: 'https://reflectionstravel.net/images/tour/large/147-Mount-Sinai-St-Catherine-Monastery-from-Sharm-El-Sheikh-10441506422660.jpeg', description: 'The Greek Orthodox monastery of the God-trodden Mount Sinai is located at the very place where God appeared to Moses in the Burning Bush, beneath the Mount of the Decalogue. In the providence of God, it is at this site also that the holy relics of Saint Catherine are enshrined. This is the oldest continuously inhabited Christian monastery, with a history that can be traced back over seventeen centuries. The monastery predates the divisions of the Christian world, its origins extending to late antiquity.'),
  Places(name: 'Jabal Mousa', location: "Egypt", price: 980, rate: 4.8, reviewNumber: 17000, categoryIndex: 0, networkImageLink: 'https://www.connollycove.com/wp-content/uploads/2022/07/Mount-Sinai-Mountains-in-Egypt-1536x1024.jpg', description: 'Mount Sinai is one of the greatest mountains in Egypt that would be a shame to miss. Apparently, it is another mountain that the lands of Sinai embraces within its borders, situated near the city of Saint Catherine as well. It elevates at a height of 2,285 meters above sea level and goes by more than a few names, with Jabal Musa being the one most commonly used. '),
  Places(name: 'Abu Rumayl', location: 'Egypt', price: 750, rate: 4.7, reviewNumber: 13000, categoryIndex: 0, networkImageLink: 'https://farm9.staticflickr.com/8187/8128422531_2f8418c46f.jpg', description: 'Jabal Abu Rumayl is one of the famous mountains in Egypt that are located in Sinai, in south Sinai in particular. You may find the name with different variations, including Abu Rumail, for example. Many of the mountains around this region are characterised with the high elevation, attracting tourists from different places around the world, and this one is no exception.'),

];
List<Places> sea = [
  Places(name: 'Mount Sinai', location: 'Egypt', price: 890, rate: 4.9, reviewNumber: 15000, categoryIndex: 0 , networkImageLink: 'https://reflectionstravel.net/images/tour/large/147-Mount-Sinai-St-Catherine-Monastery-from-Sharm-El-Sheikh-10441506422660.jpeg', description: 'The Greek Orthodox monastery of the God-trodden Mount Sinai is located at the very place where God appeared to Moses in the Burning Bush, beneath the Mount of the Decalogue. In the providence of God, it is at this site also that the holy relics of Saint Catherine are enshrined. This is the oldest continuously inhabited Christian monastery, with a history that can be traced back over seventeen centuries. The monastery predates the divisions of the Christian world, its origins extending to late antiquity.'),
  Places(name: 'Jabal Mousa', location: "Egypt", price: 980, rate: 4.8, reviewNumber: 17000, categoryIndex: 0, networkImageLink: 'https://www.connollycove.com/wp-content/uploads/2022/07/Mount-Sinai-Mountains-in-Egypt-1536x1024.jpg', description: 'Mount Sinai is one of the greatest mountains in Egypt that would be a shame to miss. Apparently, it is another mountain that the lands of Sinai embraces within its borders, situated near the city of Saint Catherine as well. It elevates at a height of 2,285 meters above sea level and goes by more than a few names, with Jabal Musa being the one most commonly used. '),
  Places(name: 'Abu Rumayl', location: 'Egypt', price: 750, rate: 4.7, reviewNumber: 13000, categoryIndex: 0, networkImageLink: 'https://farm9.staticflickr.com/8187/8128422531_2f8418c46f.jpg', description: 'Jabal Abu Rumayl is one of the famous mountains in Egypt that are located in Sinai, in south Sinai in particular. You may find the name with different variations, including Abu Rumail, for example. Many of the mountains around this region are characterised with the high elevation, attracting tourists from different places around the world, and this one is no exception.'),

];
List<Places> island = [
  Places(name: 'Mount Sinai', location: 'Egypt', price: 890, rate: 4.9, reviewNumber: 15000, categoryIndex: 0 , networkImageLink: 'https://reflectionstravel.net/images/tour/large/147-Mount-Sinai-St-Catherine-Monastery-from-Sharm-El-Sheikh-10441506422660.jpeg', description: 'The Greek Orthodox monastery of the God-trodden Mount Sinai is located at the very place where God appeared to Moses in the Burning Bush, beneath the Mount of the Decalogue. In the providence of God, it is at this site also that the holy relics of Saint Catherine are enshrined. This is the oldest continuously inhabited Christian monastery, with a history that can be traced back over seventeen centuries. The monastery predates the divisions of the Christian world, its origins extending to late antiquity.'),
  Places(name: 'Jabal Mousa', location: "Egypt", price: 980, rate: 4.8, reviewNumber: 17000, categoryIndex: 0, networkImageLink: 'https://www.connollycove.com/wp-content/uploads/2022/07/Mount-Sinai-Mountains-in-Egypt-1536x1024.jpg', description: 'Mount Sinai is one of the greatest mountains in Egypt that would be a shame to miss. Apparently, it is another mountain that the lands of Sinai embraces within its borders, situated near the city of Saint Catherine as well. It elevates at a height of 2,285 meters above sea level and goes by more than a few names, with Jabal Musa being the one most commonly used. '),
  Places(name: 'Abu Rumayl', location: 'Egypt', price: 750, rate: 4.7, reviewNumber: 13000, categoryIndex: 0, networkImageLink: 'https://farm9.staticflickr.com/8187/8128422531_2f8418c46f.jpg', description: 'Jabal Abu Rumayl is one of the famous mountains in Egypt that are located in Sinai, in south Sinai in particular. You may find the name with different variations, including Abu Rumail, for example. Many of the mountains around this region are characterised with the high elevation, attracting tourists from different places around the world, and this one is no exception.'),

];